### ISSUE TITLE
如何更改快捷键？

### ISSUE THREAD

**Issue by hhls** [mantou132/GoogleTranslate#14]
command + q 个人比较常用，想换一个快捷键，但没发现有修改的地方

**Comment by hhls** [comment]
![image](https://user-images.githubusercontent.com/23031435/61765887-7741f880-ae11-11e9-8ec0-112bb85d91f8.png)
jin'r进入到如图位置，没有返回到翻译界面的按钮

**Comment by mantou132** [comment]
暂时没做修改快捷键的功能。command+q 源码在这里：https://github.com/mantou132/GoogleTranslate/blob/google-webapp/src/main/index.ts#L159

进到不能返回的页面 command + r 刷新下

**Comment by hhls** [comment]
建议增加更换快捷键，另很多情况下(疑似没有关机直接盒盖导致)出现app白屏情况，望修复

**Comment by mantou132** [comment]
v4.1.0 可以设置快捷键了。
